[build]
  functions = "netlify/functions/"

[functions]
  node_bundler = "esbuild"
  [functions."update-database"]
    schedule = "@daily"
    # Diamo al nostro robot fino a 60 secondi per ogni esecuzione
    timeout = 60