[build]
  functions = "netlify/functions/"

[functions]
  node_bundler = "esbuild"
  [functions."update-database"]
    schedule = "@daily"
    # Aumentiamo il timeout per questa funzione specifica a 25 secondi
    timeout = 25